### PR TITLE
added ADS function readState

### PR DESCRIPTION
**Pull request by ChrisHanuta**
added ADS function readState

```javascript
var client = ads.connect(options, function() {
    this.readState(function(err,rs) {
      var text = '?';
      switch (rs.adsState) {
        case ads.ADSSTATE.INVALID:
              text = 'INVALID';
              break;
        case ads.ADSSTATE.IDLE:
              text = 'IDLE';
              break;
        case ads.ADSSTATE.RESET:
              text = 'RESET';
              break;
        case ads.ADSSTATE.INIT:
              text = 'INIT';
              break;
        case ads.ADSSTATE.START:
              text = 'START';
              break;
        case ads.ADSSTATE.RUN:
              text = 'RUN';
              break;
        case ads.ADSSTATE.STOP:
              text = 'STOP';
              break;
        case ads.ADSSTATE.SAVECFG:
              text = 'SAVECFG';
              break;
        case ads.ADSSTATE.LOADCFG:
              text = 'LOADCFG';
              break;
        case ads.ADSSTATE.POWERFAILURE:
              text = 'POWERFAILURE';
              break;
        case ads.ADSSTATE.POWERGOOD:
              text = 'POWERGOOD';
              break;
        case ads.ADSSTATE.ERROR:
              text = 'ERROR';
              break;
        case ads.ADSSTATE.SHUTDOWN:
              text = 'SHUTDOWN';
              break;
        case ads.ADSSTATE.SUSPEND:
              text = 'SUSPEND';
              break;
        case ads.ADSSTATE.RESUME:
              text = 'RESUME';
              break;
        case ads.ADSSTATE.CONFIG:
              text = 'CONFIG';
              break;
        case ads.ADSSTATE.RECONFIG:
              text = 'RECONFIG';
              break;
        case ads.ADSSTATE.STOPPING:
              text = 'STOPPING';
              break;
      }
      console.log('The state is '+text);
      this.end();
    });
})
```

### CODE REVIEW

**Comment by roccomuso** [comment]
Let's resolve conflicts and we can merge :+1:

**Comment by ChrisHanuta** [comment]
now it should work, please look over it again

**Comment by ChrisHanuta** [comment]
Thanx 👍 

Do you know Node-Red?
I want to develop a plugin for TwinCat. May I use your module as a base?
That would make many easier.

**Comment by roccomuso** [comment]
Yes. I've used it extensively. And it depends also on one of my module ([memorystore](https://npmjs.com/package/memorystore)).

Of course you can, feel free to develop a plugin.
PS. I've added you as a node-ads mantainer ;)

**Comment by ChrisHanuta** [comment]
Thanx:  
I'm just at the beginning: https://github.com/ChrisHanuta/node-red-contrib-ads

**Comment by ChrisHanuta** [comment]
Can you increase the NPM version?

**Comment by roccomuso** [comment]
Yes, we should first make sure that there are no breaking changes. And that it works flawlessly.
I'd push a `v2.0.0` right now. And then we can add the multiRead implementation as a minor `v2.1.0`.

What do you guys think @ChrisHanuta @ovi1337 ? confirm

**Comment by ChrisHanuta** [comment]
Is OK for me. But I can also live with an 1.2.0.

**Comment by ChrisHanuta** [comment]
In the Iplemantation, there are no changes to the call. All old calls work as before, I have paid attention to the compatiblity of the API.

**Comment by ovi1337** [comment]
I also think 1.2.0 makes more sense, because we don't have breaking changes for now. We should reserve us the major release v2.0.0 for a larger refactoring.

**Pull request merged**
