### PR TITLE
some extensions

### PR DESCRIPTION
**Pull request by ChrisHanuta**
Hello Rocco, I have extended the node-ads for me and corrected some errors.

maybe you want to take something from it. I can also remove some things for you.

I hope all changes come to mind:

- if requested a value as Bool, Bool will be returned, not int
- strings with a different length than 80 characters (readme.md)
- processing arrays
- correcting twicat type (array of symnames)
- improved property for the value with point
- the improved type of error by Florian
- returning the ADSSTATE text from id
- useLocalTimezone for eatch part of twicat type (array of symnames)
- improved MultiRead
- Multi Write
- get a datatype list
- something about the bytelength in the readme.md
- removed the index.js
- a parameter that do not expand arrays by getSymbols
- all strings was converted to utf8 for the pcl: the pcl only knows ASCII

I did not change the API-Calls

### CODE REVIEW

**Comment by roccomuso** [comment]
Ok, thanks!
I don't have a plc to test this changes with. Neither I saw an easy way to simulate it with docker.

I'm merging this.

**Comment by ChrisHanuta** [comment]
feel free...
Think on the npm publish

**Comment by roccomuso** [comment]
Any breaking changes to the API?
We're currently at `1.2.0` on npm.

**Comment by ChrisHanuta** [comment]
no only if requested a value as Bool, Bool will be returned, not int
all calls will work as fine as before, no chnges to the API

**Comment by ChrisHanuta** [comment]
1.4.3: get symbols and types from ADS
1.4.2: bool=bool not int
1.4.1: array
1.4.0: String length and array of type
1.3.0: multiread, multiwrite

**Comment by roccomuso** [comment]
Publishing now the 1.4.3

**Pull request merged**
