### PR TITLE
Fix notifications

### LINKED ISSUE #4: Notifications don't work
When I tried notifications, I could read the value with a handle, but I was never notified of changes.

Apparently, at line 198, there's a condition that never gets satisfied for notifications:

```js
if (ads.pending[invokeId]) {
```

It isn't invoked from the library, so there's no pending object and no callback.

Adding these two lines made the notifications work.
```js
  if (commandId == ID_NOTIFICATION) {
	getNotificationResult.call(this, data)
  } else if (ads.pending[invokeId]) //...
```

Some additional cleanup (like the removing the case and check referencing `ID_NOTIFICATION`) might be needed.

### PR DESCRIPTION
**Pull request by sanderd17**
Fixes #4

### CODE REVIEW

**Comment by roccomuso** [comment]
is this well tested? are we sure this fix doesn't introduces other issues?

**Comment by sanderd17** [comment]
Depends on your definition of "Well tested". AFAICS, there are no unit tests, so I can only speak from what I noticed.

It didn't break reading and writing (as I use that too), and it fixed notifications. That's all I tested and IMO the most important functionality.

**Comment by roccomuso** [comment]
Ok

Indeed, It would be good to have also unit test. I can give you access as mantainer if willing to.
Unfortunately I don't have any device neither enough knowledge of the bechoff products and ads to write complete unit tests.

**Comment by sanderd17** [comment]
Well, we normally use OPC-UA to communicate with Beckhoff PLCs, but for this project, I needed ADS.

I don't know if I'll be using it a lot after this project, so I don't think I'll be a good maintainer as well.

To test it, you'll probably have to mock the incoming TCP stream, and use it to answer to requests and send notifications.

**Pull request merged**
